#!/bin/sh
#
# Pre-commit hooks

# Lint stuff before committing

FILES_PATTERN='\.js(\..+)?$'

# Quit if no relevant files are being checked in.
FILES=$(git diff --cached --name-only | grep -Ec $FILES_PATTERN)
if [ "$FILES" = "0" ]; then
    exit 0
fi

# Quit if on gh-pages branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "gh-pages" ]; then
    exit 0
fi

cd "$(git rev-parse --show-toplevel)/"
grunt jshint:all
grunt jscs